### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by monoflash** [jmaks1/bitrix-frontend#1]
gulp --version
[19:28:21] CLI version 3.9.0
[19:28:21] Local version 3.9.0

Run: gulp
Result:

module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by jmaks1** [comment]
Проверьте подключаемые файлы с помощью конструкции //= (в script,js например), а также наличие установленных модулей (в node_modules), возможно не все зависимости установлены
